<a href="https://colab.research.google.com/github/Kavin4240/Machine-Learning-Projects/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def derivative_sigmoid(x):
  return x*(1-x)

In [ ]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [ ]:
output

array([[0.95580117],
       [0.06524607],
       [0.95878203]])

In [ ]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# One-hot encode labels
y_one_hot = tf.keras.utils.to_categorical(y, num_classes=3)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Define the neural network architecture using Functional API
inputs = tf.keras.Input(shape=(4,))
hidden_layer = tf.keras.layers.Dense(16, activation='relu')(inputs)
hidden_layer = tf.keras.layers.Dropout(0.2)(hidden_layer)  # Adding Dropout for regularization
output_layer = tf.keras.layers.Dense(3, activation='softmax')(hidden_layer)

# Create the model
model = tf.keras.Model(inputs=inputs, outputs=output_layer)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')


Epoch 1/100
4/4 [==============================] - 2s 273ms/step - loss: 1.7261 - accuracy: 0.4167 - val_loss: 1.2872 - val_accuracy: 0.6667
Epoch 2/100
4/4 [==============================] - 0s 37ms/step - loss: 1.6527 - accuracy: 0.3426 - val_loss: 1.2684 - val_accuracy: 0.6667
Epoch 3/100
4/4 [==============================] - 0s 47ms/step - loss: 1.6422 - accuracy: 0.3148 - val_loss: 1.2492 - val_accuracy: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 56ms/step - loss: 1.6403 - accuracy: 0.3426 - val_loss: 1.2300 - val_accuracy: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 63ms/step - loss: 1.5870 - accuracy: 0.4074 - val_loss: 1.2113 - val_accuracy: 0.6667
Epoch 6/100
4/4 [==============================] - 0s 96ms/step - loss: 1.5570 - accuracy: 0.4537 - val_loss: 1.1926 - val_accuracy: 0.6667
Epoch 7/100
4/4 [==============================] - 0s 65ms/step - loss: 1.4727 - accuracy: 0.3981 - val_loss: 1.1745 - val_accuracy: 0.5833
Epoch 8/100
4/4 [==

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions=model(x_train[:1]).numpy()
predictions

array([[ 0.53404075,  0.13993526, -0.53419244,  0.5862552 , -0.6900904 ,
        -0.6898056 , -0.39518967,  0.33252075,  0.16088426, -0.12008967]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.16446272, 0.11089441, 0.05651188, 0.1732782 , 0.04835418,
        0.04836795, 0.06493933, 0.13444617, 0.11324204, 0.08550318]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

3.0289178

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.2904 - accuracy: 0.9157
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1404 - accuracy: 0.9590
Epoch 3/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1045 - accuracy: 0.9685
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0867 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0727 - accuracy: 0.9773


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0752 - accuracy: 0.9767 - 1s/epoch - 4ms/step


[0.07522378861904144, 0.9767000079154968]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.6134329e-07, 8.6157321e-09, 1.5519082e-07, 6.5162423e-04,
        2.9755268e-11, 4.6633028e-07, 8.1250597e-11, 9.9933964e-01,
        1.9609108e-07, 7.4320678e-06],
       [3.6339326e-10, 3.0877094e-05, 9.9996483e-01, 2.8957961e-06,
        5.4067929e-14, 1.2147972e-06, 1.4226629e-08, 7.8568575e-12,
        1.6358884e-07, 3.5085270e-12],
       [2.4906998e-07, 9.9899155e-01, 5.6115725e-05, 1.2512879e-06,
        4.3311211e-05, 1.8387016e-05, 1.0023999e-05, 7.9175114e-04,
        8.6794214e-05, 6.6517288e-07],
       [9.9994397e-01, 3.7678491e-09, 3.9880499e-05, 1.3969435e-08,
        1.3472182e-07, 9.4387218e-08, 9.2890750e-06, 1.8076017e-06,
        2.3780436e-07, 4.6708578e-06],
       [1.2127957e-05, 1.3239584e-09, 1.5631318e-05, 1.3513936e-08,
        9.8091507e-01, 6.4835042e-08, 3.3575500e-06, 4.5526732e-04,
        3.6117499e-06, 1.8594855e-02]], dtype=float32)>